/**
 * buildPRDReport — 把单个 PRD 序列化为可分享的 markdown 报告。
 * 纯函数；server / client 共用。
 *
 * 9 个 section 全部按 text 段直接拼接（PRD type 故意不解析结构，导出层
 * 也不强行加 markdown 包装 —— 保留作者原始的 bullet / table 排版）。
 */

import type { PRD, MVPProject, Opportunity } from '@/types';

export interface PRDReportInput {
  generatedAt: string;
  project: PRD;
  mvpProject: MVPProject;
  opportunity?: Opportunity;
}

function fmtDate(iso: string): string {
  return iso.slice(0, 10);
}

export function buildPRDReport(input: PRDReportInput): string {
  const { generatedAt, project: p, mvpProject, opportunity } = input;
  const lines: string[] = [];

  lines.push(`# PRD — ${p.title}`);
  lines.push('');
  lines.push(`- Generated at: \`${generatedAt}\``);
  lines.push(`- PRD ID: \`${p.id}\``);
  lines.push(`- Version: **v${p.version}**`);
  lines.push(`- MVP project: [${mvpProject.name}](/mvp/${mvpProject.id}) (\`${mvpProject.id}\`)`);
  lines.push(`- MVP stage: \`${mvpProject.stage}\``);
  if (opportunity) {
    lines.push(`- Source opportunity: [${opportunity.title}](/opportunities/${opportunity.id}) (\`${opportunity.id}\`)`);
  }
  lines.push(`- Generated by mock LLM: ${p.generatedByMock ? 'yes' : 'no'}`);
  lines.push(`- Created: ${fmtDate(p.createdAt)}`);
  lines.push(`- Updated: ${fmtDate(p.updatedAt)}`);
  lines.push('');

  lines.push('## 1. 产品定位');
  lines.push('');
  lines.push(p.productPositioning);
  lines.push('');

  lines.push('## 2. 目标用户');
  lines.push('');
  lines.push(p.targetUsers);
  lines.push('');

  lines.push('## 3. 核心痛点');
  lines.push('');
  lines.push(p.corePainPoints);
  lines.push('');

  lines.push('## 4. MVP 功能范围');
  lines.push('');
  lines.push(p.mvpFeatureScope);
  lines.push('');

  lines.push('## 5. 页面结构');
  lines.push('');
  lines.push(p.pageStructure);
  lines.push('');

  lines.push('## 6. 数据模型');
  lines.push('');
  lines.push(p.dataModel);
  lines.push('');

  lines.push('## 7. API 设计');
  lines.push('');
  lines.push(p.apiDesign);
  lines.push('');

  lines.push('## 8. 验收标准');
  lines.push('');
  lines.push(p.acceptanceCriteria);
  lines.push('');

  lines.push('## 9. 7 天开发计划');
  lines.push('');
  lines.push(p.devPlan);
  lines.push('');

  lines.push('---');
  lines.push('');
  lines.push('_Auto-generated PRD report. Edit source fields in /prd/<id>._');
  return lines.join('\n');
}

export function buildPRDReportFilename(id: string): string {
  const date = new Date().toISOString().slice(0, 10);
  return `prd-${id}-${date}.md`;
}
