/**
 * Opportunity 域 mock 数据。
 *
 * 15 条 Signal → 6 个 Opportunity → 9 次 OpportunityEvaluation（多次评估）。
 * Status 覆盖 draft/evaluating/validated/mvp/archived/killed 6 个值。
 * 评估分数随时间变化，便于画趋势线。
 */

import type { Signal, Opportunity, OpportunityEvaluation } from '@/types';

/* ---------- Signal ---------- */

/*
 * 15 signals covering 11 categories. ID 前缀保持稳定以兼容
 * mockOpportunities.signalIds 引用（sig_perplexity_funding,
 * sig_openai_search_launch 等 7 个 ID 必须保留）。
 */

export const mockSignals: Signal[] = [
  {
    id: 'sig_perplexity_funding',
    title: 'Perplexity 5 亿美元融资，估值 90 亿',
    source: 'manual',
    category: 'funding',
    description: 'Perplexity 完成 $500M D 轮，估值 $9B。下游 GEO 工具 TAM 信号极强。',
    evidence: 'TechCrunch 2026-05-15 报道；领投方 NEA / IVP，跟投 Bessemer。',
    confidence: 92,
    linkedEntityIds: ['entity_perplexity'],
    linkedResearchCardIds: ['card_perplexity_signal'],
    createdAt: '2026-05-15T08:00:00.000Z',
    updatedAt: '2026-05-15T08:00:00.000Z',
  },
  {
    id: 'sig_openai_search_launch',
    title: 'OpenAI SearchGPT 公测',
    source: 'https://openai.com/index/searchgpt/',
    category: 'product_launch',
    description: 'OpenAI 正式向所有用户开放 SearchGPT，AI 搜索竞争白热化。',
    evidence: 'OpenAI 官方博客 + Verge 报道。',
    confidence: 95,
    linkedEntityIds: ['entity_openai'],
    linkedResearchCardIds: ['card_4_player_landscape'],
    createdAt: '2026-04-20T09:00:00.000Z',
    updatedAt: '2026-04-20T09:00:00.000Z',
  },
  {
    id: 'sig_apple_intelligence',
    title: 'Apple Intelligence 系统级 AI',
    source: 'https://www.apple.com/newsroom/',
    category: 'product_launch',
    description: 'Apple 在 iOS 18 / macOS 15 集成系统级 AI，引用源集中在 Apple News + Wikipedia。',
    evidence: 'WWDC 2024 主题演讲；第一方流量优势。',
    confidence: 88,
    linkedEntityIds: ['entity_apple'],
    linkedResearchCardIds: ['card_aarw_principle'],
    createdAt: '2024-06-11T08:00:00.000Z',
    updatedAt: '2024-06-11T08:00:00.000Z',
  },
  {
    id: 'sig_nyt_perplexity_lawsuit',
    title: 'NYT 起诉 Perplexity',
    source: 'manual',
    category: 'regulation',
    description: 'NYT 起诉 Perplexity 未授权使用内容。AI 答案版权风险上升。',
    evidence: 'NYT 诉状 2026-06-10 提交；引用生成路径成为被告主张核心。',
    confidence: 90,
    linkedEntityIds: ['entity_perplexity', 'entity_nyt'],
    linkedResearchCardIds: ['card_brand_narrative_diff'],
    createdAt: '2026-06-11T08:00:00.000Z',
    updatedAt: '2026-06-11T08:00:00.000Z',
  },
  {
    id: 'sig_geo_paper',
    title: 'GEO 论文发表',
    source: 'https://arxiv.org/abs/2311.09735',
    category: 'technology_breakthrough',
    description: 'Princeton 团队发表首篇 GEO 论文，定义 AARW 原则。',
    evidence: 'Krishna et al. 2023, "Generative Engine Optimization"。',
    confidence: 95,
    linkedEntityIds: ['entity_princeton_geo'],
    linkedResearchCardIds: ['card_aarw_principle', 'card_geo_definition'],
    createdAt: '2026-03-01T09:00:00.000Z',
    updatedAt: '2026-03-01T09:00:00.000Z',
  },
  {
    id: 'sig_mcp_release',
    title: 'MCP 协议开源',
    source: 'https://modelcontextprotocol.io',
    category: 'technology_breakthrough',
    description: 'Anthropic 开源 Model Context Protocol，LLM 工具集成标准化。',
    evidence: 'GitHub anthropics/mcp 在 6 个月内 star 突破 30k。',
    confidence: 90,
    linkedEntityIds: ['entity_anthropic'],
    linkedResearchCardIds: [],
    createdAt: '2024-11-26T09:00:00.000Z',
    updatedAt: '2024-11-26T09:00:00.000Z',
  },
  {
    id: 'sig_anthropic_computer_use',
    title: 'Anthropic Computer Use 公测',
    source: 'https://www.anthropic.com/news/3-5-sonnet-and-computer-use',
    category: 'product_launch',
    description: 'Anthropic 推出 Computer Use，AI 直接操作桌面 UI。',
    evidence: 'API 文档 + 多个 demo 视频。',
    confidence: 85,
    linkedEntityIds: ['entity_anthropic'],
    linkedResearchCardIds: [],
    createdAt: '2025-10-23T08:00:00.000Z',
    updatedAt: '2025-10-23T08:00:00.000Z',
  },
  /* --- additional signals covering remaining categories --- */
  {
    id: 'sig_langchain_github_trend',
    title: 'LangGraph 周 star 增长 1.2k',
    source: 'github-trending-connector',
    category: 'github_trend',
    description: 'LangGraph 在 2026-06 第三周 GitHub trending 上冲到 Python 周榜第二。',
    evidence: 'github.com/langchain-ai/langgraph；trending API 拉取。',
    confidence: 70,
    linkedEntityIds: ['entity_langchain'],
    linkedResearchCardIds: [],
    createdAt: '2026-06-20T09:00:00.000Z',
    updatedAt: '2026-06-20T09:00:00.000Z',
  },
  {
    id: 'sig_anthropic_hiring_agent',
    title: 'Anthropic 招聘 30+ Agent 工程师',
    source: 'rss-connector:anthropic-jobs',
    category: 'hiring_signal',
    description: 'Anthropic 公开招聘 agent 方向工程师 30+，集中在 SF 与伦敦。',
    evidence: 'jobs.anthropic.com 2026-06 抓取。',
    confidence: 80,
    linkedEntityIds: ['entity_anthropic'],
    linkedResearchCardIds: [],
    createdAt: '2026-06-15T09:00:00.000Z',
    updatedAt: '2026-06-15T09:00:00.000Z',
  },
  {
    id: 'sig_customer_pain_seo_agency',
    title: 'SEO agency 抱怨 GEO 报告缺数据',
    source: 'manual:interview-2026-06',
    category: 'customer_pain',
    description: '6 家 SEO agency 反馈：现有 GEO 工具价格高 ($1k+/月) 但报告缺关键平台覆盖。',
    evidence: '30 分钟访谈 × 6；记录在 customer-pain/2026-06-seo-agency.md。',
    confidence: 65,
    linkedEntityIds: [],
    linkedResearchCardIds: ['card_ai_search_disruption'],
    createdAt: '2026-06-18T10:00:00.000Z',
    updatedAt: '2026-06-18T10:00:00.000Z',
  },
  {
    id: 'sig_eu_ai_act_2026',
    title: 'EU AI Act 高风险条款生效',
    source: 'news-connector:reuters',
    category: 'regulation',
    description: '欧盟 AI 法案高风险条款于 2026-08 生效，影响 AI 答案生成产品的合规设计。',
    evidence: 'Reuters 2026-06 政策跟踪报道。',
    confidence: 95,
    linkedEntityIds: [],
    linkedResearchCardIds: [],
    createdAt: '2026-06-22T09:00:00.000Z',
    updatedAt: '2026-06-22T09:00:00.000Z',
  },
  {
    id: 'sig_tiktok_geo_search',
    title: 'TikTok 测试答案型搜索结果',
    source: 'rss-connector:tiktok-news',
    category: 'short_video_trend',
    description: 'TikTok 在 App 内测试 answer-engine 形态的搜索结果页，引用视频卡 + 第三方链接。',
    evidence: 'SocialMediaToday 2026-06 报道；用户录屏。',
    confidence: 55,
    linkedEntityIds: ['entity_tiktok'],
    linkedResearchCardIds: [],
    createdAt: '2026-06-10T09:00:00.000Z',
    updatedAt: '2026-06-10T09:00:00.000Z',
  },
  {
    id: 'sig_patent_llm_citation',
    title: 'Google 申请 LLM 引用排序专利',
    source: 'patent-connector:uspto',
    category: 'ip_trend',
    description: 'Google 申请专利：把 LLM 答案的引用排序做成可学习的 policy。',
    evidence: 'USPTO 公开号 2026-06-09；专利文档节选。',
    confidence: 78,
    linkedEntityIds: ['entity_google'],
    linkedResearchCardIds: [],
    createdAt: '2026-06-12T09:00:00.000Z',
    updatedAt: '2026-06-12T09:00:00.000Z',
  },
  {
    id: 'sig_reddit_geo_content',
    title: 'r/GEO 订阅突破 10k',
    source: 'reddit-connector',
    category: 'content_trend',
    description: 'r/GEO 订阅 4 个月内从 0 增长到 10k+，GEO 关键词在英文内容平台显著上升。',
    evidence: 'reddit.com/r/GEO；同样关键词在 Substack 月发文 2026 年增 4x。',
    confidence: 72,
    linkedEntityIds: [],
    linkedResearchCardIds: [],
    createdAt: '2026-06-08T09:00:00.000Z',
    updatedAt: '2026-06-08T09:00:00.000Z',
  },
  {
    id: 'sig_mckinsey_ai_search',
    title: 'McKinsey 发布 AI 搜索影响报告',
    source: 'news-connector:mckinsey',
    category: 'geo_trend',
    description: 'McKinsey 报告：到 2028 年 AI 答案占搜索查询 25% 以上，SEO 预算 30% 迁移。',
    evidence: 'McKinsey 2026-05 报告；引用 12 个一手数据。',
    confidence: 80,
    linkedEntityIds: ['entity_mckinsey'],
    linkedResearchCardIds: ['card_ai_search_disruption'],
    createdAt: '2026-05-28T09:00:00.000Z',
    updatedAt: '2026-05-28T09:00:00.000Z',
  },
];


/* ---------- Opportunity ---------- */

/*
 * 6 mock opportunities, status 分布覆盖 draft/evaluating/validated/mvp/
 * archived/killed 6 个值。relatedSignalIds / relatedResearchCardIds /
 * relatedEntityIds 引用 mock 上方已存在的实体。
 */

export const mockOpportunities: Opportunity[] = [
  {
    id: 'opp_geo_monitor',
    title: 'GEO 监控 SaaS',
    description: 'AI 引擎时代品牌可见度监控与竞品对比的 SaaS 平台。',
    targetUser: '北美 B2B 品牌营销负责人 (CMO / 品牌经理)',
    painPoint: '品牌方不知道自家在 ChatGPT / Claude / Perplexity 答案里被怎么描述，也无法系统化跟踪竞品差异。',
    solutionIdea: '按品牌 / query 维度抓取主流 AI 引擎答案 + 引用源，生成可对比的可见度报告与告警。',
    status: 'mvp',
    relatedSignalIds: ['sig_perplexity_funding', 'sig_openai_search_launch', 'sig_mckinsey_ai_search'],
    relatedResearchCardIds: ['card_geo_definition', 'card_perplexity_signal', 'card_4_player_landscape'],
    relatedEntityIds: ['entity_perplexity', 'entity_openai'],
    createdAt: '2026-05-18T09:00:00.000Z',
    updatedAt: '2026-06-22T14:30:00.000Z',
  },
  {
    id: 'opp_citation_optimizer',
    title: '引用优化服务',
    description: '把现有品牌内容改写成 AI 引擎更愿意引用的「AI 友好版」内容。',
    targetUser: '已经有内容团队的中型 B2B 品牌',
    painPoint: '品牌不仅想看自己被怎么引用，还想直接拿到一份「AI 友好版」内容改写服务。',
    solutionIdea: '基于 Research Card 的 evidence 与 insights，针对每个监控 query 生成可发布的改写内容 + AARW 评分。',
    status: 'evaluating',
    relatedSignalIds: ['sig_openai_search_launch', 'sig_geo_paper'],
    relatedResearchCardIds: ['card_aarw_principle', 'card_brand_narrative_diff'],
    relatedEntityIds: ['entity_princeton_geo'],
    createdAt: '2026-04-25T10:00:00.000Z',
    updatedAt: '2026-06-20T11:00:00.000Z',
  },
  {
    id: 'opp_aarw_consulting',
    title: 'AARW 咨询服务',
    description: '面向 Fortune 500 的 AARW (Add, Author, Refine, Watch) 专家咨询服务。',
    targetUser: 'Fortune 500 品牌营销高管',
    painPoint: '高端品牌没有内部 AARW 专家；GEO 论文刚发表，市场上几乎没有可信赖的实施顾问。',
    solutionIdea: '$20-50K 项目费，6 周交付：诊断当前 AI 可见度 + 制定 AARW 实施手册。',
    status: 'killed',
    relatedSignalIds: ['sig_geo_paper'],
    relatedResearchCardIds: ['card_aarw_principle'],
    relatedEntityIds: ['entity_princeton_geo'],
    createdAt: '2026-03-10T10:00:00.000Z',
    updatedAt: '2026-05-30T12:00:00.000Z',
  },
  {
    id: 'opp_brand_narrative_kit',
    title: '品牌叙事工具包',
    description: '为中小品牌提供 AI 引导式「叙事品牌」输出工具包。',
    targetUser: '独立 DTC 品牌创始人',
    painPoint: '中小品牌没有品牌战略团队，无法系统化产出可在 AI 答案里被引用的「品牌叙事」内容。',
    solutionIdea: '模板化的品牌 pillar / story arc 工具 + 监测哪些 query 触发自家品牌叙事。',
    status: 'draft',
    relatedSignalIds: ['sig_apple_intelligence', 'sig_openai_search_launch', 'sig_reddit_geo_content'],
    relatedResearchCardIds: ['card_brand_narrative_diff'],
    relatedEntityIds: ['entity_apple'],
    createdAt: '2026-06-05T10:00:00.000Z',
    updatedAt: '2026-06-15T09:00:00.000Z',
  },
  {
    id: 'opp_ai_search_seo',
    title: 'AI 搜索 SEO 工具',
    description: '面向 SEO agency 的 AI 搜索版 SEMrush，覆盖关键词 + 引用 + 平台维度。',
    targetUser: 'SEO agency / in-house SEO team',
    painPoint: '传统 SEO 工具没有 AI 答案维度；agency 客户问「ChatGPT 怎么引用我们」时无法回答。',
    solutionIdea: '在传统 SEO 工具上加 AI 答案层：监控 query、答案内容、引用源分布、竞品对比。',
    status: 'archived',
    relatedSignalIds: ['sig_openai_search_launch', 'sig_mckinsey_ai_search', 'sig_customer_pain_seo_agency'],
    relatedResearchCardIds: ['card_ai_search_disruption'],
    relatedEntityIds: [],
    createdAt: '2026-05-20T10:00:00.000Z',
    updatedAt: '2026-06-18T10:00:00.000Z',
  },
  {
    id: 'opp_brand_narrative_academy',
    title: '品牌叙事学院',
    description: '面向品牌营销人员的 AARW + 品牌叙事在线课程 + 认证体系。',
    targetUser: '品牌营销人员 (in-house + agency junior)',
    painPoint: '市场上缺乏系统化的 AARW 培训，团队自学成本高。',
    solutionIdea: '8 周在线课程 + 实战 case 评审 + 校友社群；订阅制 $99/月。',
    status: 'validated',
    relatedSignalIds: ['sig_reddit_geo_content', 'sig_geo_paper'],
    relatedResearchCardIds: ['card_aarw_principle', 'card_brand_narrative_diff'],
    relatedEntityIds: [],
    createdAt: '2026-04-10T10:00:00.000Z',
    updatedAt: '2026-06-12T11:00:00.000Z',
  },
];

/* ---------- OpportunityEvaluation ---------- */

export const mockOpportunityEvaluations: OpportunityEvaluation[] = [
  /*
   * 9 evaluations covering 6 opportunities; totalScore spans 47-77 so
   * ranking page shows real differentiation.
   */
  // ---- opp_geo_monitor x 3 (time series) ----
  {
    id: 'eval_geo_monitor_1',
    opportunityId: 'opp_geo_monitor',
    marketSize: 75,
    painIntensity: 70,
    competition: 55,
    technicalFeasibility: 70,
    monetization: 65,
    speedToMarket: 75,
    founderFit: 80,
    geoPotential: 90,
    ipPotential: 40,
    totalScore: 69.5,
    explanation: 'GEO monitoring market has clear TAM; pain is real (multi-platform coverage is hard). Competitors Otterly / Profound exist, but SMB positioning differentiates. Technical scraping carries moderate compliance risk; 6-8 weeks to MVP.',
    createdAt: '2026-05-20T09:00:00.000Z',
    updatedAt: '2026-05-20T09:00:00.000Z',
  },
  {
    id: 'eval_geo_monitor_2',
    opportunityId: 'opp_geo_monitor',
    marketSize: 80,
    painIntensity: 75,
    competition: 60,
    technicalFeasibility: 75,
    monetization: 70,
    speedToMarket: 80,
    founderFit: 80,
    geoPotential: 90,
    ipPotential: 45,
    totalScore: 73.0,
    explanation: 'Bump up: 12 of 20 trial brands willing to pay $500/mo. Crawler and answer-diff algorithm stable. Recommend approval to start MVP.',
    createdAt: '2026-06-05T09:00:00.000Z',
    updatedAt: '2026-06-05T09:00:00.000Z',
  },
  {
    id: 'eval_geo_monitor_3',
    opportunityId: 'opp_geo_monitor',
    marketSize: 85,
    painIntensity: 80,
    competition: 55,
    technicalFeasibility: 80,
    monetization: 75,
    speedToMarket: 80,
    founderFit: 85,
    geoPotential: 95,
    ipPotential: 50,
    totalScore: 77.0,
    explanation: 'Latest: B2B willingness-to-pay reconfirmed. Team is highly aligned with this direction. Promote to MVP pipeline.',
    createdAt: '2026-06-22T14:00:00.000Z',
    updatedAt: '2026-06-22T14:00:00.000Z',
  },
  // ---- opp_citation_optimizer x 2 ----
  {
    id: 'eval_citation_opt_1',
    opportunityId: 'opp_citation_optimizer',
    marketSize: 60,
    painIntensity: 65,
    competition: 65,
    technicalFeasibility: 60,
    monetization: 60,
    speedToMarket: 70,
    founderFit: 75,
    geoPotential: 85,
    ipPotential: 35,
    totalScore: 63.5,
    explanation: 'Mid-strength eval. Pain is real but delivery chain is long; clients need in-house content team.',
    createdAt: '2026-05-10T10:00:00.000Z',
    updatedAt: '2026-05-10T10:00:00.000Z',
  },
  {
    id: 'eval_citation_opt_2',
    opportunityId: 'opp_citation_optimizer',
    marketSize: 65,
    painIntensity: 70,
    competition: 60,
    technicalFeasibility: 65,
    monetization: 65,
    speedToMarket: 70,
    founderFit: 75,
    geoPotential: 90,
    ipPotential: 40,
    totalScore: 67.0,
    explanation: 'GEO potential confirmed. Suggest a $200/mo "lite" tier to validate SMB segment.',
    createdAt: '2026-06-20T11:00:00.000Z',
    updatedAt: '2026-06-20T11:00:00.000Z',
  },
  // ---- opp_aarw_consulting x 1 (low score, killed) ----
  {
    id: 'eval_aarw_1',
    opportunityId: 'opp_aarw_consulting',
    marketSize: 35,
    painIntensity: 30,
    competition: 75,
    technicalFeasibility: 90,
    monetization: 50,
    speedToMarket: 30,
    founderFit: 50,
    geoPotential: 70,
    ipPotential: 25,
    totalScore: 47.0,
    explanation: 'Consulting TAM is small, decision chain long. Team not a fit for sales-led motion. Low technical bar; revenue ceiling low.',
    createdAt: '2026-05-30T12:00:00.000Z',
    updatedAt: '2026-05-30T12:00:00.000Z',
  },
  // ---- opp_brand_narrative_kit x 1 ----
  {
    id: 'eval_brand_kit_1',
    opportunityId: 'opp_brand_narrative_kit',
    marketSize: 50,
    painIntensity: 60,
    competition: 70,
    technicalFeasibility: 65,
    monetization: 55,
    speedToMarket: 65,
    founderFit: 70,
    geoPotential: 65,
    ipPotential: 30,
    totalScore: 58.0,
    explanation: 'Draft stage. SMB pain is real but purchasing power is limited. Need 5+ user interviews to confirm ICP.',
    createdAt: '2026-06-15T09:00:00.000Z',
    updatedAt: '2026-06-15T09:00:00.000Z',
  },
  // ---- opp_ai_search_seo x 1 (low score, parked) ----
  {
    id: 'eval_ai_seo_1',
    opportunityId: 'opp_ai_search_seo',
    marketSize: 70,
    painIntensity: 55,
    competition: 30, // very low -> red ocean
    technicalFeasibility: 60,
    monetization: 60,
    speedToMarket: 50,
    founderFit: 50,
    geoPotential: 75,
    ipPotential: 30,
    totalScore: 54.5,
    explanation: 'SEMrush / Ahrefs dominate. Technically buildable but channel and brand gap too large. Recommend parking.',
    createdAt: '2026-06-18T10:00:00.000Z',
    updatedAt: '2026-06-18T10:00:00.000Z',
  },
  // ---- opp_brand_narrative_academy x 1 (high score, validated) ----
  {
    id: 'eval_brand_academy_1',
    opportunityId: 'opp_brand_narrative_academy',
    marketSize: 65,
    painIntensity: 75,
    competition: 80,
    technicalFeasibility: 90,
    monetization: 70,
    speedToMarket: 70,
    founderFit: 85,
    geoPotential: 60,
    ipPotential: 40,
    totalScore: 71.5,
    explanation: 'Subscription + certification model is clean. Team has content ops experience. Low competition.',
    createdAt: '2026-06-12T11:00:00.000Z',
    updatedAt: '2026-06-12T11:00:00.000Z',
  },
];
