/**
 * Research 域 mock 数据。
 *
 * 故事线：团队围绕 "GEO 工具市场" 主题在跑 5 个并行研究，
 * 收集了 7 份外部资料，浓缩出 8 张可独立消费的研究卡片。
 *
 * ID 命名：topic_xxx / src_xxx / card_xxx，全局唯一。
 */

import type {
  ResearchTopic,
  SourceItem,
  ResearchCard,
} from '@/types';

/* ---------- ResearchTopic ---------- */

export const mockResearchTopics: ResearchTopic[] = [
  {
    id: 'topic_geo_market_2026',
    title: 'GEO 工具市场 2026',
    description: '跟踪 GEO 监控 / 优化赛道 2026 的市场规模、玩家、增长曲线。',
    category: 'geo',
    priority: 'high',
    tags: ['tam', 'landscape', '2026'],
    question: '2026 年 Generative Engine Optimization 工具市场的规模、玩家和增长曲线？',
    scope: '聚焦 B2B SaaS 形态的 GEO 监控 / 优化工具，不含咨询服务。',
    status: 'active',
    ownerId: 'agent_research_lead',
    sourceIds: ['src_perplexity_funding', 'src_openai_search_launch', 'src_geo_paper_krishna', 'src_mckinsey_ai_search'],
    cardIds: ['card_geo_definition', 'card_perplexity_signal', 'card_4_player_landscape', 'card_ai_search_disruption'],
    signalIds: ['sig_perplexity_funding', 'sig_openai_search_launch', 'sig_geo_paper'],
    createdAt: '2026-04-12T09:00:00.000Z',
    updatedAt: '2026-06-22T14:30:00.000Z',
  },
  {
    id: 'topic_ai_citation_mech',
    title: 'AI 引擎引用机制',
    description: '拆解 ChatGPT / Perplexity / Claude 等主流引擎的网页引用流程，沉淀可观察的优化面。',
    category: 'ai',
    priority: 'high',
    tags: ['rag', 'grounding', 'mechanism'],
    question: 'ChatGPT / Perplexity / Claude 等如何选择要引用的网页？',
    scope: '研究检索增强生成（RAG）和 web grounding 的工作原理。',
    status: 'active',
    ownerId: 'agent_research_lead',
    sourceIds: ['src_openai_search_launch', 'src_apple_wwdc_2024'],
    cardIds: ['card_citation_method', 'card_apple_intelligence_signal'],
    signalIds: ['sig_openai_search_launch', 'sig_apple_intelligence'],
    createdAt: '2026-04-20T10:00:00.000Z',
    updatedAt: '2026-06-20T11:00:00.000Z',
  },
  {
    id: 'topic_competitor_landscape',
    title: '竞品图谱',
    description: '梳理 4 家主要 GEO 玩家的产品定位、客户画像、能力边界。',
    category: 'geo',
    priority: 'medium',
    tags: ['competitor', 'positioning'],
    question: '当前有哪些 GEO 玩家？各自定位和能力边界？',
    scope: 'Otterly / Profound / AI SEO 等 4 家。',
    status: 'active',
    sourceIds: ['src_nyt_perplexity_lawsuit', 'src_mckinsey_ai_search'],
    cardIds: ['card_4_player_landscape', 'card_brand_narrative_diff'],
    signalIds: ['sig_nyt_perplexity_lawsuit'],
    createdAt: '2026-05-08T13:00:00.000Z',
    updatedAt: '2026-06-15T09:00:00.000Z',
  },
  {
    id: 'topic_brand_narrative_eng',
    title: '品牌叙事工程',
    description: '把品牌改写成 AI 引擎更愿引用的形态：叙事结构、llms.txt、结构化数据。',
    category: 'geo',
    priority: 'medium',
    tags: ['narrative', 'aarw', 'llms-txt'],
    question: '在 AI 答案里如何让品牌被正确识别和引用？',
    scope: '围绕 AARW 原则和 llms.txt 等结构化数据。',
    status: 'active',
    ownerId: 'agent_research_lead',
    sourceIds: ['src_geo_paper_krishna', 'src_mcp_release'],
    cardIds: ['card_aarw_principle', 'card_brand_narrative_diff'],
    signalIds: ['sig_geo_paper', 'sig_mcp_release'],
    createdAt: '2026-05-15T08:00:00.000Z',
    updatedAt: '2026-06-10T16:00:00.000Z',
  },
  {
    id: 'topic_aarw_principles',
    title: 'AARW 引用原则',
    description: '把 AARW 4 个改写策略沉淀为可复用的内容 checklist。',
    category: 'geo',
    priority: 'low',
    tags: ['aarw', 'methodology'],
    question: 'GEO 论文提出的 Add · Assert · Refute · Weigh 原则怎么落地？',
    scope: '聚焦"把内容改成 AI 更愿引用的形式"的具体方法。',
    status: 'completed',
    sourceIds: ['src_geo_paper_krishna'],
    cardIds: ['card_aarw_principle'],
    signalIds: ['sig_geo_paper'],
    createdAt: '2026-03-01T10:00:00.000Z',
    updatedAt: '2026-04-30T12:00:00.000Z',
  },
  {
    id: 'topic_short_video_ai_creator',
    title: 'AI 短内容创作者工具',
    description: '盘点 2026 帮助短内容创作者降本增效的 AI 工具：脚本生成 / 数字人 / 剪辑。',
    category: 'short_video',
    priority: 'medium',
    tags: ['creator-economy', 'ai-tools'],
    question: '2026 哪些 AI 工具在帮短内容创作者提升产出效率？',
    scope: '聚焦 B2C 创作者市场，不含企业级视频平台。',
    status: 'active',
    sourceIds: [],
    cardIds: [],
    signalIds: [],
    createdAt: '2026-06-18T10:00:00.000Z',
    updatedAt: '2026-06-24T11:00:00.000Z',
  },
  {
    id: 'topic_saas_pricing_2025',
    title: 'SaaS 定价实验 2025',
    description: '回顾 2025 主要 B2B SaaS 公司的定价调整：PLG → 企业版的迁移。',
    category: 'saas',
    priority: 'low',
    tags: ['pricing', 'plg', '2025'],
    status: 'archived',
    sourceIds: [],
    cardIds: [],
    signalIds: [],
    createdAt: '2025-09-01T10:00:00.000Z',
    updatedAt: '2026-02-15T12:00:00.000Z',
  },
];

/* ---------- SourceItem ---------- */

export const mockSourceItems: SourceItem[] = [
  {
    id: 'src_perplexity_funding',
    title: 'Perplexity 完成 5 亿美元融资，估值 90 亿',
    url: 'https://example.com/perplexity-funding-2026',
    type: 'article',
    author: 'TechCrunch',
    publishedAt: '2026-05-15T00:00:00.000Z',
    summary: 'Perplexity AI 在新一轮融资中筹得 5 亿美元，公司估值达到 90 亿美元。本轮由 B 资本领投。',
    credibilityScore: 88,
    tags: ['funding', 'perplexity', 'geo'],
    topicId: 'topic_geo_market_2026',
    createdAt: '2026-05-15T08:00:00.000Z',
    updatedAt: '2026-05-15T08:00:00.000Z',
  },
  {
    id: 'src_openai_search_launch',
    title: 'OpenAI 推出 SearchGPT 公测版',
    url: 'https://example.com/openai-searchgpt',
    type: 'article',
    author: 'OpenAI Blog',
    publishedAt: '2026-04-20T00:00:00.000Z',
    summary: 'OpenAI 正式向所有用户开放 SearchGPT，整合实时网页检索与对话式回答。',
    credibilityScore: 90,
    tags: ['openai', 'search', 'product-launch'],
    topicId: 'topic_ai_citation_mech',
    createdAt: '2026-04-20T09:00:00.000Z',
    updatedAt: '2026-04-20T09:00:00.000Z',
  },
  {
    id: 'src_geo_paper_krishna',
    title: 'GEO: Generative Engine Optimization 论文',
    url: 'https://arxiv.org/abs/2311.09735',
    type: 'paper',
    author: 'Krishna et al. (Princeton)',
    publishedAt: '2023-11-16T00:00:00.000Z',
    summary: '论文首次系统提出 GEO 概念，并提出 AARW 内容改写原则。',
    credibilityScore: 95,
    tags: ['geo', 'aarw', 'methodology'],
    topicId: 'topic_aarw_principles',
    createdAt: '2026-03-01T09:00:00.000Z',
    updatedAt: '2026-03-01T09:00:00.000Z',
  },
  {
    id: 'src_apple_wwdc_2024',
    title: 'Apple Intelligence - WWDC 2024',
    url: 'https://example.com/wwdc2024',
    type: 'video',
    author: 'Apple Newsroom',
    publishedAt: '2024-06-10T00:00:00.000Z',
    summary: 'Apple 推出系统级 AI 集成，深度整合 OpenAI / 自研模型。',
    credibilityScore: 92,
    tags: ['apple', 'platform', 'wwdc'],
    topicId: 'topic_ai_citation_mech',
    createdAt: '2024-06-11T08:00:00.000Z',
    updatedAt: '2024-06-11T08:00:00.000Z',
  },
  {
    id: 'src_mckinsey_ai_search',
    title: 'McKinsey: AI 搜索将吞掉 25% 的传统搜索广告',
    url: 'https://example.com/mckinsey-ai-search',
    type: 'report',
    author: 'McKinsey',
    publishedAt: '2026-06-01T00:00:00.000Z',
    summary: '到 2028 年，AI 搜索将占据搜索查询总量的 25%，影响约 800 亿美元广告市场。',
    credibilityScore: 85,
    tags: ['market', 'forecast', 'mckinsey'],
    topicId: 'topic_geo_market_2026',
    createdAt: '2026-06-02T09:00:00.000Z',
    updatedAt: '2026-06-02T09:00:00.000Z',
  },
  {
    id: 'src_mcp_release',
    title: 'Model Context Protocol 协议开源',
    url: 'https://modelcontextprotocol.io',
    type: 'website',
    author: 'Anthropic',
    publishedAt: '2024-11-25T00:00:00.000Z',
    summary: 'Anthropic 开源 MCP 协议，让 LLM 与外部工具/数据源标准化连接。',
    credibilityScore: 80,
    tags: ['mcp', 'protocol', 'anthropic'],
    topicId: 'topic_brand_narrative_eng',
    createdAt: '2024-11-26T09:00:00.000Z',
    updatedAt: '2024-11-26T09:00:00.000Z',
  },
  {
    id: 'src_nyt_perplexity_lawsuit',
    title: '纽约时报起诉 Perplexity',
    url: 'https://example.com/nyt-perplexity',
    type: 'article',
    author: '纽约时报',
    publishedAt: '2026-06-10T00:00:00.000Z',
    summary: 'NYT 起诉 Perplexity 未经授权使用其内容作为 AI 回答来源。',
    credibilityScore: 87,
    tags: ['legal', 'nyt', 'perplexity'],
    topicId: 'topic_competitor_landscape',
    createdAt: '2026-06-11T08:00:00.000Z',
    updatedAt: '2026-06-11T08:00:00.000Z',
  },
];

/* ---------- ResearchCard ---------- */

export const mockResearchCards: ResearchCard[] = [
  {
    id: 'card_geo_definition',
    topicId: 'topic_geo_market_2026',
    sourceIds: ['src_geo_paper_krishna'],
    title: 'GEO 定义与边界',
    summary: 'Generative Engine Optimization (GEO) 指针对生成式 AI 搜索/回答引擎优化品牌可见度的实践。区别于 SEO 优化"网页排名"，GEO 优化"被 AI 引用为权威来源"。',
    keyInsights: [
      'GEO 是 SEO 的继任者，关注点从"网页排名"转向"被 AI 引用"',
      '论文 2023 年首次提出，2026 年成为独立赛道',
      '与传统 SEO 不互斥，可叠加',
    ],
    evidence: [
      'Krishna et al. (2023) 论文: arxiv.org/abs/2311.09735',
    ],
    risks: [
      '定义尚未标准化，不同厂商的"GEO score"含义差异大',
    ],
    tags: ['definition', 'geo', 'seo'],
    score: 90,
    graphEntityIds: ['entity_geo'],
    createdAt: '2026-04-13T09:00:00.000Z',
    updatedAt: '2026-04-13T09:00:00.000Z',
  },
  {
    id: 'card_aarw_principle',
    topicId: 'topic_brand_narrative_eng',
    sourceIds: ['src_geo_paper_krishna'],
    title: 'AARW 改写原则',
    summary: 'GEO 论文提出 4 种内容改写策略：Add (补全关键统计)、Assert (加明确主张)、Refute (反驳常见误解)、Weigh (权衡对立观点)。实验显示可见度提升 30-40%。',
    keyInsights: [
      'AARW = Add / Assert / Refute / Weigh 四类改写动作',
      '论文实验显示可见度提升 30-40%',
      '适用于任何被 AI 引用的内容（FAQ / blog / 文档）',
    ],
    evidence: [
      'Krishna et al. (2023) Table 2: 改写后 citation rate +30-40%',
    ],
    risks: [
      '实验环境是 GPT-3.5；其他模型效果可能不同',
      '过度 Refute / Weigh 可能降低可读性',
    ],
    tags: ['aarw', 'methodology', 'geo'],
    score: 85,
    graphEntityIds: ['entity_aarw', 'entity_geo'],
    createdAt: '2026-03-05T10:00:00.000Z',
    updatedAt: '2026-04-30T12:00:00.000Z',
  },
  {
    id: 'card_perplexity_signal',
    topicId: 'topic_geo_market_2026',
    sourceIds: ['src_perplexity_funding'],
    title: 'Perplexity 融资是 GEO 工具市场的强信号',
    summary: 'AI 搜索答案供应商的高估值，间接证明下游 GEO 优化需求存在。Perplexity 的 90 亿估值 → GEO 工具 TAM 不应低于 Perplexity 营收的 5%。',
    keyInsights: [
      'AI 搜索答案供应商的高估值 = 下游 GEO 需求强劲的强信号',
      'TAM 反推：GEO 工具市场 ≥ Perplexity 营收 × 5%',
      '估值上行 → GEO 工具的"年付意愿" 同步上行',
    ],
    evidence: [
      'TechCrunch: Perplexity $500M / $9B valuation (2026-05)',
    ],
    risks: [
      'TAM 估算依赖 Perplexity 营收假设（不公开）',
      '若 Perplexity 自研 GEO 工具，独立 GEO 工具空间被压缩',
    ],
    tags: ['market', 'tam', 'signal'],
    score: 75,
    graphEntityIds: ['entity_perplexity'],
    signalId: 'sig_perplexity_funding',
    createdAt: '2026-05-16T09:00:00.000Z',
    updatedAt: '2026-05-16T09:00:00.000Z',
  },
  {
    id: 'card_ai_search_disruption',
    topicId: 'topic_geo_market_2026',
    sourceIds: ['src_mckinsey_ai_search', 'src_openai_search_launch'],
    title: 'AI 搜索颠覆传统 SEO',
    summary: 'McKinsey 预测 2028 年 AI 搜索占 25% 查询量。意味着 SEO 工具市场（$80B）会有 30% 转移到 GEO 工具，TAM 至少有 $20B。',
    keyInsights: [
      '2028 年 AI 搜索占 25% 查询量（McKinsey 预测）',
      'SEO 工具市场 ($80B) 中 30% 转移 → GEO TAM ≥ $20B',
      'OpenAI SearchGPT 公测 = 转折点已过',
    ],
    evidence: [
      'McKinsey 2026 报告: AI 搜索 25% query share by 2028',
      'SearchGPT 公测: openai.com/searchgpt',
    ],
    risks: [
      'McKinsey 预测可能过于乐观（类似"移动优先"过度预测）',
      '转移率 30% 是粗估，实际可能更低',
    ],
    tags: ['market', 'disruption', 'seo'],
    score: 80,
    graphEntityIds: ['entity_openai'],
    createdAt: '2026-06-03T10:00:00.000Z',
    updatedAt: '2026-06-22T14:00:00.000Z',
  },
  {
    id: 'card_brand_narrative_diff',
    topicId: 'topic_brand_narrative_eng',
    sourceIds: ['src_mcp_release', 'src_nyt_perplexity_lawsuit'],
    title: '叙事品牌 vs 功能品牌',
    summary: 'AI 更倾向引用有清晰叙事的品牌（"我们相信 X"），而不是纯功能品牌（"我们做 Y"）。后者引用率比前者低 40%。',
    keyInsights: [
      '叙事品牌引用率 +40% vs 功能品牌',
      'AI 引擎把"有立场"等同于"权威"',
      'MCP 让 brand 可以程序化声明叙事结构',
    ],
    evidence: [
      'GPT-4 引用率实验: 叙事 vs 功能（n=500）',
      'MCP 协议: modelcontextprotocol.io',
    ],
    risks: [
      '实验数据未公开，难以复核',
      '"叙事"难定义，可能被滥用为 storytelling 而非真观点',
    ],
    tags: ['narrative', 'brand', 'positioning'],
    score: 70,
    graphEntityIds: ['entity_aarw', 'entity_perplexity'],
    createdAt: '2026-05-20T10:00:00.000Z',
    updatedAt: '2026-06-10T16:00:00.000Z',
  },
  {
    id: 'card_4_player_landscape',
    topicId: 'topic_geo_market_2026',
    sourceIds: ['src_mckinsey_ai_search'],
    title: '4 大 GEO 玩家图谱',
    summary: 'Otterly (品牌监控)、Profound (B2B 分析)、AI SEO (SMB 工具)、Conductor (老牌 SEO 转 GEO)。Otterly 在产品体验领先，Profound 客户深度最强。',
    keyInsights: [
      'Otterly: 品牌监控体验领先（UX best-in-class）',
      'Profound: B2B 客户深度最强（enterprise）',
      'AI SEO: SMB 入门级工具，价格低',
      'Conductor: 老牌 SEO 厂商转型 GEO',
    ],
    evidence: [
      'McKinsey 2026 竞品矩阵',
      'Otterly.ai 产品 demo（2026-05）',
    ],
    risks: [
      '图谱变化快，3 个月内可能有新玩家',
      '厂商定位可能重叠（Otterly vs Profound）',
    ],
    tags: ['competitor', 'landscape'],
    score: 70,
    graphEntityIds: ['entity_cognitive_venture_os'],
    createdAt: '2026-06-05T10:00:00.000Z',
    updatedAt: '2026-06-15T09:00:00.000Z',
  },
  {
    id: 'card_citation_method',
    topicId: 'topic_ai_citation_mech',
    sourceIds: ['src_openai_search_launch', 'src_apple_wwdc_2024'],
    title: '引用检查方法论',
    summary: '用真实 AI 查询（30+ 条）按月跑，把"被引用" + "提及但未引用"两个维度打标签，结合 brand 资产 id 反查被引用资产。',
    keyInsights: [
      '30+ 条真实 query 按月调度是 baseline',
      '2 维度判定：cited / mentioned-only / absent / competitor-only',
      '结合 brand 资产 id 反查 = 知道被引用的具体是哪个页面',
    ],
    evidence: [
      'OpenAI SearchGPT response inspection (2026-04)',
      'Apple Intelligence response pattern (WWDC 2024)',
    ],
    risks: [
      'AI 答案非确定性，month-over-month 波动 10-15%',
      '30 条 query 样本量偏小，统计显著性受限',
    ],
    tags: ['methodology', 'monitoring'],
    score: 80,
    graphEntityIds: ['entity_geo', 'entity_openai'],
    createdAt: '2026-04-25T10:00:00.000Z',
    updatedAt: '2026-06-20T11:00:00.000Z',
  },
  {
    id: 'card_apple_intelligence_signal',
    topicId: 'topic_ai_citation_mech',
    sourceIds: ['src_apple_wwdc_2024'],
    title: 'Apple Intelligence 影响 AI 引用',
    summary: 'Apple Intelligence 在系统级拦截查询，引用源以 Apple News + Wikipedia 为主，长尾内容几乎不被引用。这意味着品牌还需要进入结构化数据源。',
    keyInsights: [
      'Apple Intelligence 引用源 = Apple News + Wikipedia 为主',
      '长尾内容引用率趋近 0',
      '品牌需要进入结构化数据源（schema.org / Wikidata）',
    ],
    evidence: [
      'WWDC 2024 keynote: Apple Intelligence grounding',
    ],
    risks: [
      'Wikipedia 引用受社区编辑影响，brand 难以直接控制',
      '结构化数据源的覆盖度差异大',
    ],
    tags: ['apple', 'platform', 'citation'],
    score: 65,
    graphEntityIds: ['entity_google', 'entity_openai'],
    createdAt: '2024-06-15T10:00:00.000Z',
    updatedAt: '2026-06-20T11:00:00.000Z',
  },
];
