/**
 * PRDDraftNotice — "[mock] Generated by LLMProvider" 提示条。RSC。
 *
 * 当 PRD 由 mock LLMProvider 生成时显示，提醒编辑者内容是 mock 草稿
 * 起点、需要人工审校。
 */
export function PRDDraftNotice({ visible }: { visible: boolean }) {
  if (!visible) return null;
  return (
    <div
      role="status"
      className="rounded-md border border-warn/40 bg-warn/5 px-3 py-2 text-xs text-warn"
    >
      <span className="font-medium">[mock]</span> Generated by mock
      LLMProvider. Treat as a draft starting point — review and rewrite before
      committing.
    </div>
  );
}
