/**
 * PRDList — 列表视图（已按 mvpProjectId 分组后的单组渲染）。
 * RSC；服务层负责按 version desc 排序。
 */
import Link from 'next/link';
import { Card } from '@/components/ui/Card';
import { Badge } from '@/components/ui/Badge';
import { PRDVersionBadge } from './PRDVersionBadge';
import type { PRD } from '@/types';

interface Row {
  prd: PRD;
}

function fmtDate(iso: string): string {
  return iso.slice(0, 10);
}

export function PRDList({ rows }: { rows: Row[] }) {
  if (rows.length === 0) {
    return (
      <Card>
        <div className="text-sm text-muted">
          No PRDs for this MVP project yet. Generate one to get started.
        </div>
      </Card>
    );
  }
  return (
    <Card className="p-0 overflow-hidden">
      <table className="w-full text-sm">
        <thead className="bg-panel-2 text-muted">
          <tr className="text-left">
            <th className="px-4 py-2 font-medium">Version</th>
            <th className="px-4 py-2 font-medium">Title</th>
            <th className="px-4 py-2 font-medium">Source</th>
            <th className="px-4 py-2 font-medium">Updated</th>
          </tr>
        </thead>
        <tbody>
          {rows.map(({ prd }) => (
            <tr
              key={prd.id}
              className="border-t border-border hover:bg-panel-2 transition"
            >
              <td className="px-4 py-2.5">
                <div className="flex items-center gap-1.5">
                  <PRDVersionBadge version={prd.version} />
                  {prd.generatedByMock && (
                    <Badge tone="warn" aria-label="Generated by mock LLM">
                      mock
                    </Badge>
                  )}
                </div>
              </td>
              <td className="px-4 py-2.5">
                <Link
                  href={`/prd/${prd.id}`}
                  className="text-text hover:text-accent font-medium"
                >
                  {prd.title}
                </Link>
                <div className="text-xs text-muted mt-0.5 font-mono">
                  {prd.id}
                </div>
              </td>
              <td className="px-4 py-2.5 text-xs text-muted">
                <Link
                  href={`/mvp/${prd.mvpProjectId}`}
                  className="text-muted hover:text-accent"
                >
                  {prd.mvpProjectId}
                </Link>
              </td>
              <td className="px-4 py-2.5 text-xs text-muted">
                {fmtDate(prd.updatedAt)}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </Card>
  );
}
